{% set version = "1.8" %}

package:
  name: topojson
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/topojson/topojson-{{ version }}.tar.gz
  sha256: 1363933c31cd9ba3dd9cf9df96bbd3ffe56126bd0396f0295a41b48c5666de08

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3
    - pip
    - flit
  run:
    - python >=3
    - numpy
    - shapely
    - packaging

test:
  imports:
    - topojson

about:
  home: "https://github.com/mattijn/topojson"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "topojson - a powerful library to encode spatial data as topology in Python!"
  doc_url: https://mattijn.github.io/topojson
  dev_url: https://github.com/mattijn/topojson

extra:
  recipe-maintainers:
    - mattijn
